# Generated by Django 5.1.4 on 2025-01-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('slug', models.TextField()),
                ('name', models.TextField()),
                ('release_date', models.DateField(blank=True)),
                ('tba', models.BooleanField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('platforms', models.TextField(blank=True)),
                ('developers', models.TextField(blank=True)),
                ('genres', models.TextField(blank=True)),
                ('publishers', models.TextField(blank=True)),
                ('esrb_rating', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('title', models.TextField()),
                ('all_percent', models.FloatField(blank=True)),
                ('all_rating', models.TextField(blank=True)),
                ('tc_percent', models.FloatField(blank=True)),
                ('tc_rating', models.TextField(blank=True)),
                ('user_percent', models.FloatField(blank=True)),
                ('user_rating', models.TextField(blank=True)),
                ('critics_consensus', models.TextField(blank=True)),
            ],
        ),
    ]
