# Generated by Django 5.1.4 on 2025-01-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockGameoMeter', '0002_gameinfo_poster_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescores',
            name='all_percent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gamescores',
            name='tc_percent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gamescores',
            name='user_percent',
            field=models.IntegerField(),
        ),
    ]
