# Generated by Django 5.1.4 on 2025-01-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockGameoMeter', '0003_alter_gamescores_all_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescores',
            name='mock_mc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamescores',
            name='all_percent',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='gamescores',
            name='tc_percent',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='gamescores',
            name='user_percent',
            field=models.IntegerField(blank=True),
        ),
    ]
