# Generated by Django 5.1.4 on 2025-01-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockGameoMeter', '0005_alter_gamescores_critics_consensus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescores',
            name='all_percent',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='gamescores',
            name='id_number',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gamescores',
            name='mock_mc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamescores',
            name='tc_percent',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='gamescores',
            name='user_percent',
            field=models.FloatField(blank=True),
        ),
    ]
