# Generated by Django 5.1.4 on 2025-01-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockGameoMeter', '0006_alter_gamescores_all_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescores',
            name='id_number',
            field=models.IntegerField(),
        ),
    ]
