# Generated by Django 5.1.4 on 2025-01-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockGameoMeter', '0007_alter_gamescores_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescores',
            name='mock_mc',
            field=models.FloatField(blank=True, default=-1),
            preserve_default=False,
        ),
    ]
