# Generated by Django 5.1.4 on 2025-01-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockGameoMeter', '0008_alter_gamescores_mock_mc'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescores',
            name='all_symbol',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
