# Generated by Django 5.1.4 on 2025-01-10 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockGameoMeter', '0010_gamescores_tc_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamescores',
            name='all_symbol',
        ),
        migrations.RemoveField(
            model_name='gamescores',
            name='tc_symbol',
        ),
    ]
