# Generated by Django 5.1.4 on 2025-01-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockGameoMeter', '0011_remove_gamescores_all_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescores',
            name='all_symbol',
            field=models.IntegerField(blank=True, default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamescores',
            name='tc_symbol',
            field=models.IntegerField(blank=True, default=5.0),
            preserve_default=False,
        ),
    ]
