# Generated by Django 5.1.4 on 2025-01-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockGameoMeter', '0012_gamescores_all_symbol_gamescores_tc_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescores',
            name='all_symbol',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='gamescores',
            name='tc_symbol',
            field=models.FloatField(blank=True),
        ),
    ]
