# Generated by Django 5.1.4 on 2025-01-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockGameoMeter', '0013_alter_gamescores_all_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescores',
            name='user_symbol',
            field=models.FloatField(blank=True, default=2.0),
            preserve_default=False,
        ),
    ]
