# Generated by Django 5.1.4 on 2025-01-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockGameoMeter', '0014_gamescores_user_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescores',
            name='critics_consensus',
            field=models.TextField(blank=True, max_length=40000, null=True),
        ),
    ]
