# Generated by Django 5.1.4 on 2025-01-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockGameoMeter', '0015_alter_gamescores_critics_consensus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescores',
            name='critics_consensus',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
