# Generated by Django 5.1.4 on 2025-01-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockGameoMeter', '0016_alter_gamescores_critics_consensus'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='critics_score',
            field=models.TextField(blank=True, null=True),
        ),
    ]
