# Generated by Django 5.2.1 on 2025-05-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockGameoMeter', '0017_gameinfo_critics_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaBars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('score_list', models.TextField()),
            ],
        ),
    ]
