# Generated by Django 5.2.1 on 2025-05-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockGameoMeter', '0018_metabars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metabars',
            name='score_list',
            field=models.JSONField(),
        ),
    ]
